# Amount of seconds in between every broadcast
Cooldown-interval: 10
Messages:
  1:
    Permission: ""
    Sound: ""
    Message: "This is a single-line broadcast"
  2:
    Permission: ""
    Sound:
    Message:
      - "This is a"
      - "Multi-line"
      - "Broadcast"

Language:
  Prefix: "&e&l(&c&l!&e&l) "
  Invalid-subcommand: "&c&lYou have entered an invalid subcommand!"
  Not-enough-arguments: "&c&lNot enough arguments!"